language: php

php:
  - 5.6

services:
  - sqlite

## Run on container environment
sudo: false

## Cache composer bits
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - cp .env.travis .env
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - php artisan key:generate

script: travis_retry php vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - travis_retry php vendor/bin/coveralls -v